language: java
jdk:
  - oraclejdk9
os: osx
#install: ant deps
script:
  - echo "Running Tests"
  - bundle exec rake spec
  - echo "Linting the documentation for Danger's internal plugins"
  - bundle exec danger plugins lint lib/danger/danger_core/plugins/*.rb --warnings-as-errors
  - echo "Running the Dangerfile for this repo"
  - bundle exec danger --verbose
  - echo "Validating that danger init is working fine"
  - bundle exec danger init --mousey --impatient
